config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # resources :movies
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:create, :new]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: {minimum: 6}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:destroy]

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.new(bookmark_params)
    if @bookmark.save!
      redirect_to @list, notice: 'Bookmark was successfully added.'
    else
      render 'lists/show'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to @bookmark.list, notice: 'Bookmark was successfully removed.'
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]
  def index
    @lists = List.all
  end

  def show; end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

 private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  def index
    @movies = Movie.all
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.save
    redirect_to movie_path(@movie) #taking to show
  end

  def edit
  end

  def update
    @movie.update(movie_params)
    redirect_to movie_path(@movie) #taking to show
  end

  def destroy
    @movie.destroy
    redirect_to movies_path(@movie), status: :see_other#taking to index
  end

 private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for(bookmark) do |f| %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/bookmarks/create.html.erb
<h1>Create a new Bookmark</h1>

app/views/bookmarks/destroy.html.erb
<h1>Delete Bookmark</h1>
<%= link_to "Delete",
  bookmark_path(@bookmark),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

app/views/bookmarks/new.html.erb
<h1>Add a movie to bookmark</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit class:"btn btn-primary"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/create.html.erb
<h1>Create a new List</h1>

app/views/lists/index.html.erb
<h1>Lists</h1>
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>
<%= link_to "Create a new list", new_list_path %>

app/views/lists/new.html.erb
<div class="container mt-5">
  <h1>Add a new list</h1>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<h2><%= "#{@list.name}" %></h2>
<% @list.bookmarks.each do |bookmark| %>
<%= bookmark.movie.title %>
<%= link_to "Delete",
  bookmark_path(bookmark),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
<br>
<% end %>
<br>
<%= link_to "Create a new Bookmark", new_list_bookmark_path(@list) %>
<br>
<%= link_to "Return to Lists index", lists_path %>

app/views/movies/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/destroy.html.erb
<h1>Delete Movie</h1>
<%= link_to "Delete",
  movie_path(@movie),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>
<%= form_with model: @movie do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :overview %>
  <%= f.text_field :overview %>
  <%= f.label :poster_url %>
  <%= f.text_field :poster_url %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/movies/index.html.erb
<h1>Movies</h1>
<ul>
  <% @movies.each do |movie| %>
    <li><%= link_to movie.title, movie_path(movie) %></li>
  <% end %>
</ul>

app/views/movies/new.html.erb
<h1>Add a new Movie</h1>
<%= form_with model: @movie do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :overview %>
  <%= f.text_field :overview %>
  <%= f.label :poster_url %>
  <%= f.text_field :poster_url %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/movies/show.html.erb
<h2><%= "Title: #{@movie.title}" %></h2>
<p><%= "Overview: #{@movie.overview}" %></p>
<p><%= "Poster URL: #{@movie.poster_url}" %></p>
<p><%= "Rating: #{@movie.rating}" %></p>
<%= link_to "Delete", movies_path %>
<%= link_to "Return to List of Movies", movies_path %>

app/views/movies/update.html.erb
<h1>Movies#update</h1>
<p>Find me in app/views/movies/update.html.erb</p>